# Definition of the GitHub action as per https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
#
# Uses GITHUB_TOKEN, GPG_PRIVATE_KEY, INFECTION_DASHBOARD_API_KEY, CODECOV_TOKEN environment variables
# see https://docs.github.com/en/actions/reference/environment-variables

name: 'ghostwriter/compliance'
description: 'Compliance - CI/CD & QA Test Automation for PHP via GitHub Actions.'

author: Nathanael Esayeas (@ghostwriter)

branding:
  icon: triangle
  color: green

outputs:
  matrix:
    description: 'JSON string: Job matrix for Github Actions.'

runs:
  image: docker://ghcr.io/ghostwriter/compliance:v1
  using: docker
