name: Compliance Automation

on:
  pull_request:
  push:
    branches:
      - "[0-9]+.[0-9]+.x"
      - "v[0-9]+"
  schedule:
    - cron: "0 * * * *" # Runs hourly

jobs:
  matrix:
    name: Generate job matrix
    runs-on: ubuntu-latest
    outputs:
      jobs: ${{ steps.matrix.outputs.jobs }}
    steps:
      - name: Determine CI Jobs
        id: jobs
        uses: ghostwriter/compliance@v1
        with:
          command: matrix
#  qa:
#    name: QA Checks
#    needs: [matrix]
#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix: ${{ fromJSON(needs.matrix.outputs.jobs) }}
#    steps:
#      - name: ${{ matrix.name }}
#        uses: ghostwriter/compliance@v1
#        with:
#          command: check
#          job: ${{ matrix.job }}
